name: check-install-sh
on: [push]
jobs:
  run-install-sh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: cache libpostal download and build
        id: cache-libpostal
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/cache
          key: ${{ runner.os }}-libpostal

#     - name: install libpostal dependencies
#       run: sudo apt-get install curl autoconf automake libtool pkg-config

      - name: build libpostal
        if: steps.cache-libpostal.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ github.workspace }}/cache/downloads
          cd ${{ github.workspace }}/cache
          git clone https://github.com/openvenues/libpostal
          cd libpostal
          ./bootstrap.sh
          ./configure --datadir=${{ github.workspace }}/cache/downloads
          sudo make

      - name: install libpostal
        run: |
          mkdir -p ${{ github.workspace }}/cache/libpostal
          cd ${{ github.workspace }}/cache/libpostal
          sudo make install

      - name: run SDK install script
        run: cd ${{ github.workspace }} && ls -al && ./install.sh

