name: check-install-sh
on: [push]
jobs:
  run-install-sh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: le sigh
        run: pwd

      - name: cache libpostal download and build
        id: cache-libpostal
        uses: actions/cache@v3
        with:
          path: |
            libpostal
            /usr/local/share/libpostal
          key: ${{ runner.os }}-libpostal

      - name: build libpostal
        if: steps.cache-libpostal.outputs.cache-hit != 'true'
        run: |
          cd ~
          git clone https://github.com/openvenues/libpostal
          cd libpostal
          ./bootstrap.sh
          ./configure
          sudo make

      - name: install libpostal
        run: |
          cd ~
          cd libpostal
          sudo make install

      - name: run SDK install script
        run: cd /genie-sdk && ls -al && ./install.sh
        run: cd / && ls -al

